### ISSUE TITLE
Cannot click global join farm button

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-ui#379]
User joined in one farm but not the second one. This prevents user to click join farm button (He can join if he expands detail)

<img width="1151" alt="Screenshot 2023-03-23 at 17 06 08" src="https://user-images.githubusercontent.com/3409250/227267113-75607f18-eefc-4973-89e7-5ed251d5eb4f.png">

<img width="1164" alt="Screenshot 2023-03-23 at 17 06 25" src="https://user-images.githubusercontent.com/3409250/227267091-10989e59-28da-4fbb-9739-1655de75d7b6.png">

**Comment by obsivac-cleevio** [comment]
In this case, the disabled Join Farm button is for joining all farms and creating a new farming position. It's disabled because the user doesn't have any liquidity shares, so he can't create a new position.

I think this is the intended use case. We could expand the functionality by always checking all farming positions to see whether a new farm is available to join just for that position, then change the functionality of that button to invoke a different modal window for redepositing the shares of that position to the new farm, and repeat the process for all possible positions. But I think this would be a bit unnecessary and complicated and would harm performance with more requests and calculations on the main page.

**Comment by obsivac-cleevio** [comment]
@jak-pan do you think we can close this issue?

**Comment by jak-pan** [comment]
Not yet. We will want to enable this in some way but it's lower prio. We were talking about just showing a button which would say some farms are joinable and it would just expand the rollup so you can see the joinable farms as a quickfix.
